tqsdk:
  username: tq-username
  password: tq-password
  interval: [182, 365, 547, 730]
email:
  account: email-account
  password: email-password
  smtp_host: smtp.qq.com
  smtp_port: 465
  receivers:
    - abc@qq.com
    - def@qq.com
