tqsdk:
  username: tq-username
  password: tq-password
  intervals: [91, 182, 365, 547]
email:
  enable: false
  account: email-account
  password: email-password
  smtp_host: smtp.qq.com
  smtp_port: 465
  receivers:
    - abc@qq.com
    - def@qq.com
html:
  enable: true
  path: /var/www/html
  filename: tqsdk.html
